name: Run Transcriptometer

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set execute permission on script
        run: chmod +x transcriptometer.sh

      - name: Install dependencies (gnuplot)
        run: sudo apt-get update && sudo apt-get install -y gnuplot

      - name: Run Transcriptometer on test.fasta
        run: ./transcriptometer.sh test.fasta
