name: Run Transcriptometer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gnuplot

    - name: Make script executable
      run: chmod +x transcriptometer.sh
    
    - name: Run transcriptometer script
      run: ./transcriptometer.sh test.fasta
